apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-nats
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: messaging
  install:
    createNamespace: true
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
      interval: 1h
