apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: pingpong-data
          persistentVolumeClaim:
            claimName: course-part1-claim
      containers:
        - name: pingpong
          image: pingpong
          imagePullPolicy: Never
          env:
           - name: PINGPONG_PATH
             value: "/opt/data/pingpong.data"
          volumeMounts:
          - name: pingpong-data
            mountPath: /opt/data