micronaut:
  application:
    name: server
    picture:
      source: https://picsum.photos/1200
      cache: ${PICTURE_CACHE:.}
  server:
    port: ${PORT:8080}
netty:
  default:
    allocator:
      max-order: 3
