apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-rollouts
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: argo-rollouts
  install:
    createNamespace: true
  chart:
    spec:
      chart: argo-rollouts
      sourceRef:
        kind: HelmRepository
        name: argo-community
        namespace: flux-system
      interval: 1h