apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - manifests/configmap-db.yaml
  - manifests/cronjob-readwiki.yaml
#  - manifests/deployment-backend.yaml
  - manifests/deployment-frontend.yaml
  - manifests/deployment-picture.yaml
  - manifests/deployment-broadcaster.yaml
  - manifests/ingress.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/secret.yaml
  - manifests/service-backend.yaml
  - manifests/service-frontend.yaml
  - manifests/service-picture.yaml
  - manifests/service-postgres.yaml
  - manifests/statefulset-postgres.yaml
  - manifests/rollout-backend.yaml
  - manifests/analysistemplate-backend.yaml
