apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backend-analysis
spec:
  metrics:
  - name: ns-cpu-rate
    initialDelay: 2m
    successCondition: result < 0.25
    provider:
      prometheus:
        address: http://monitoring-prometheus-kube-prometheus.monitoring.svc.cluster.local:9090/prometheus/
        query: |
          scalar(sum(rate(container_cpu_usage_seconds_total{namespace="project"}[8m])))