apiVersion: batch/v1
kind: CronJob
metadata:
  name: readwiki
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: readwiki
            image: project-readwiki
            imagePullPolicy: Never
            env:
            - name: TODOS
              value: "http://backend-svc/todos"
            resources:
              limits:
                cpu: 250m
                memory: 128M
              requests:
                cpu: 25m
                memory: 32M
          restartPolicy: Never