apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-picture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-picture
  template:
    metadata:
      labels:
        app: project-picture
    spec:
      volumes:
        - name: pictures-data
          persistentVolumeClaim:
            claimName: course-part1-claim
      containers:
        - name: project-picture
          image: project-picture
          imagePullPolicy: Never
          env:
           - name: PICTURE_CACHE
             value: "/opt/data"
          volumeMounts:
          - name: pictures-data
            mountPath: /opt/data