apiVersion: v1
kind: Service
metadata:
  name: project-backend-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: project-backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080