name: 'build-publish-deploy'
description: 'Builds an image and publishes it to Docker Hub and adjusts deployment file'

inputs:
  image:
    description: "generic image name"
    required: true
  tag:
    description: "docker tag to use"
    required: true
  docker-context:
    description: "docker context location"
    required: true
  kustomize-context:
    description: "kustomize context location"
    required: true

runs:
  using: "composite"
  steps:
   - name: Login to Docker Hub
     uses: docker/login-action@v1
     with:
       username: ${{ env.DOCKER_USERNAME }}
       password: ${{ env.DOCKER_PASSWORD }}
   - name: Build and Push
     uses: docker/build-push-action@v2
     with:
       context: ${{ inputs.docker-context }}
       push: true
       tags: ${{ inputs.tag }}
   - name: Set up Kustomize
     uses: imranismail/setup-kustomize@v1
   - name: Pull latest changes
     shell: bash
     run: git pull
   - name: Update deployment
     working-directory: ${{ inputs.kustomize-context }}
     shell: bash
     run: |-
         kustomize edit set image ${{ inputs.image }}=${{ inputs.tag }}
   - uses: EndBug/add-and-commit@v9
     with:
       add: '${{ inputs.kustomize-context }}/kustomization.yaml'
       message: New version release ${{ inputs.tag }}
       pull: '--rebase --autostash'
     env:
       GITHUB_TOKEN: ${{ github.token }}
