apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: exercises
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: knative-contour
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./Exercises
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age