name: Build Project Readwiki

on:
  push:
    paths:
      - 'Project/project-readwiki/**'
      - '.github/workflows/build-project-readwiki.yaml'
      - '.github/actions/build-publish/action.yaml'

jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Build, publish and adjust deployment files
        uses: ./.github/actions/build-publish
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          image: project-readwiki
          tag: ${{ secrets.DOCKER_USERNAME }}/project-readwiki:${{ github.sha }}
          docker-context: Project/project-readwiki
          kustomize-context: Project
