name: Build DummySites Controller

on:
  push:
    paths:
      - 'DummySite/controller/**'
      - '.github/workflows/build-dummysites-controller.yaml'
      - '.github/actions/build-publish/action.yaml'

jobs:
  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Build, publish and adjust deployment files
        uses: ./.github/actions/build-publish
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          image: dummysites-controller
          tag: ${{ secrets.DOCKER_USERNAME }}/dummysites-controller:${{ github.sha }}
          docker-context: DummySite/controller
          kustomize-context: DummySite
